### ISSUE TITLE
Hitbox determinism and playables

### ISSUE THREAD

**Issue by FleshMobProductions** [KnightlessLabs/Platform-Fighter-Engine#1]
Hi, I am a spare time game developer that also wants to make a deterministic platform fighter. 

This is not really a feature request, more like a question regarding future implementations. I couldn't find any contact data of you, so I wrote my question here: 

Is it possible to bind hitboxes to bodyparts when Playables are used? Or would all hitbox data have to be stored separately completely separated by the animation system? How do you plan to tackle the problem of hitbox data determinism for animations? 

I have read that Playables are lightweight animation components, But I guess they will not provide deterministic transform/position data for a body part for a specific frame across all platforms, or am I wrong? 

Kind regards

**Comment by FleshMobProductions** [comment]
Also, thank you for the great resource! I also started to use TrueSync for determinism. Sadly, the fixed math operations are very slow and the development has discontinued (it will be replaced by Photon QUANTUM)

**Comment by christides11** [comment]
Thanks for the interest, from what I understand playables should be deterministic since it makes use of the Animator component (found something [here](https://github.com/Unity-Technologies/SimpleAnimation/wiki#simpleanimation-doesnt-support-only-writing-the-values-of-the-current-clip-by-default) that suggest it's deterministic), however I'll be testing it soon to make sure. If not I'll probably go the way of decoupling hitboxes from bones for now.      
It's been a while since I've worked on this (was waiting for something to due with TrueSync, forgot now), but since TrueSync is dead I'll first have to look into ways to get deterministic physics, either myself or through other libraries. I've updated my profile with contact information if you need it.
